services:
  database:
    image: "postgres:17"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moni
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
